# Gregorian Events and Holidays - Complete Version
# رویدادها و تعطیلات میلادی - نسخه کامل

gregorian_events_en = {
    # January
    (1,1): "New Year's Day",
    (1,4): "World Braille Day",
    (1,24): "International Day of Education",
    (1,26): "International Day of Clean Energy",
    (1,27): "International Day of Commemoration in Memory of the Victims of the Holocaust",
    (1,28): "International Day of Peaceful Coexistence",
    
    # February
    (2,2): "World Wetlands Day",
    (2,4): "International Day of Human Fraternity",
    (2,6): "International Day of Zero Tolerance to Female Genital Mutilation",
    (2,10): "World Pulses Day",
    (2,10): "International Day of the Arabian Leopard",
    (2,11): "International Day of Women and Girls in Science",
    (2,12): "International Day for the Prevention of Violent Extremism as and when Conducive to Terrorism",
    (2,13): "World Radio Day",
    (2,17): "Global Tourism Resilience Day",
    (2,20): "World Day of Social Justice",
    (2,21): "International Mother Language Day",
    
    # March
    (3,1): "Zero Discrimination Day",
    (3,1): "World Seagrass Day",
    (3,3): "World Wildlife Day",
    (3,5): "International Day for Disarmament and Non-Proliferation Awareness",
    (3,8): "International Women's Day",
    (3,10): "International Day of Women Judges",
    (3,15): "International Day to Combat Islamophobia",
    (3,20): "International Day of Happiness",
    (3,20): "French Language Day",
    (3,21): "World Day for Glaciers",
    (3,21): "International Day for the Elimination of Racial Discrimination",
    (3,21): "International Day of Forests",
    (3,21): "World Poetry Day",
    (3,21): "International Day of Nowruz",
    (3,21): "World Down Syndrome Day",
    (3,22): "World Water Day",
    (3,23): "World Meteorological Day",
    (3,24): "World Tuberculosis Day",
    (3,24): "International Day for the Right to the Truth concerning Gross Human Rights Violations and for the Dignity of Victims",
    (3,25): "International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade",
    (3,25): "International Day of Solidarity with Detained and Missing Staff Members",
    (3,30): "International Day of Zero Waste",
    
    # April
    (4,2): "World Autism Awareness Day",
    (4,4): "International Day for Mine Awareness and Assistance in Mine Action",
    (4,5): "International Day of Conscience",
    (4,6): "International Day of Sport for Development and Peace",
    (4,7): "International Day of Reflection on the 1994 Genocide against the Tutsi in Rwanda",
    (4,7): "World Health Day",
    (4,12): "International Day of Human Space Flight",
    (4,14): "World Chagas Disease Day",
    (4,20): "Chinese Language Day",
    (4,21): "World Creativity and Innovation Day",
    (4,22): "International Mother Earth Day",
    (4,23): "World Book and Copyright Day",
    (4,23): "English Language Day",
    (4,23): "Spanish Language Day",
    (4,24): "International Girls in ICT Day",
    (4,24): "International Day of Multilateralism and Diplomacy for Peace",
    (4,25): "World Malaria Day",
    (4,25): "International Delegate's Day",
    (4,26): "International Chernobyl Disaster Remembrance Day",
    (4,26): "World Intellectual Property Day",
    (4,28): "World Day for Safety and Health at Work",
    (4,29): "International Day in Memory of the Victims of Earthquakes",
    (4,30): "International Jazz Day",
    
    # May
    (5,2): "World Tuna Day",
    (5,3): "World Press Freedom Day",
    (5,5): "World Portuguese Language Day",
    (5,8): "Time of Remembrance and Reconciliation for Those Who Lost Their Lives During the Second World War",
    (5,10): "International Day of Argania",
    (5,10): "World Migratory Bird Day",
    (5,12): "International Day of Plant Health",
    (5,12): "Vesak, the Day of the Full Moon",
    (5,15): "International Day of Families",
    (5,16): "International Day of Living Together in Peace",
    (5,16): "International Day of Light",
    (5,17): "World Telecommunication and Information Society Day",
    (5,19): "World Fair Play Day",
    (5,20): "World Bee Day",
    (5,21): "International Tea Day",
    (5,21): "World Day for Cultural Diversity for Dialogue and Development",
    (5,22): "International Day for Biological Diversity",
    (5,23): "International Day to End Obstetric Fistula",
    (5,24): "International Day of the Markhor",
    (5,25): "World Football Day",
    (5,29): "International Day of UN Peacekeepers",
    (5,30): "International Day of Potato",
    (5,31): "World No-Tobacco Day",
    
    # June
    (6,1): "Global Day of Parents",
    (6,3): "World Bicycle Day",
    (6,4): "International Day of Innocent Children Victims of Aggression",
    (6,5): "World Environment Day",
    (6,5): "International Day for the Fight against Illegal, Unreported and Unregulated Fishing",
    (6,6): "Russian Language Day",
    (6,7): "World Food Safety Day",
    (6,8): "World Oceans Day",
    (6,10): "International Day for Dialogue among Civilizations",
    (6,11): "International Day of Play",
    (6,12): "World Day Against Child Labour",
    (6,13): "International Albinism Awareness Day",
    (6,14): "World Blood Donor Day",
    (6,15): "World Elder Abuse Awareness Day",
    (6,16): "International Day of Family Remittances",
    (6,17): "World Day to Combat Desertification and Drought",
    (6,18): "Sustainable Gastronomy Day",
    (6,18): "International Day for Countering Hate Speech",
    (6,19): "International Day for the Elimination of Sexual Violence in Conflict",
    (6,20): "World Refugee Day",
    (6,21): "International Day of Yoga",
    (6,21): "International Day of the Celebration of the Solstice",
    (6,23): "United Nations Public Service Day",
    (6,23): "International Widows' Day",
    (6,24): "International Day of Women in Diplomacy",
    (6,25): "Day of the Seafarer",
    (6,26): "International Day against Drug Abuse and Illicit Trafficking",
    (6,26): "United Nations International Day in Support of Victims of Torture",
    (6,27): "International Day of Deafblindness",
    (6,27): "Micro-, Small and Medium-sized Enterprises Day",
    (6,29): "International Day of the Tropics",
    (6,30): "International Asteroid Day",
    (6,30): "International Day of Parliamentarism",
    
    # July
    (7,5): "International Day of Cooperatives",
    (7,6): "World Rural Development Day",
    (7,7): "World Kiswahili Language Day",
    (7,7): "World Horse Day",
    (7,11): "World Population Day",
    (7,11): "International Day of Reflection and Commemoration of the 1995 Genocide in Srebrenica",
    (7,12): "International Day of Combating Sand and Dust Storms",
    (7,12): "International Day of Hope",
    (7,15): "World Youth Skills Day",
    (7,18): "Nelson Mandela International Day",
    (7,20): "World Chess Day",
    (7,20): "International Moon Day",
    (7,25): "International Day of Women and Girls of African Descent",
    (7,25): "World Drowning Prevention Day",
    (7,25): "International Day for Judicial Well-being",
    (7,28): "World Hepatitis Day",
    (7,30): "International Day of Friendship",
    (7,30): "World Day against Trafficking in Persons",
    
    # August
    (8,6): "International Day of Awareness of the Special Development Needs and Challenges of Landlocked Developing Countries",
    (8,9): "International Day of the World's Indigenous Peoples",
    (8,11): "World Steelpan Day",
    (8,12): "International Youth Day",
    (8,19): "World Humanitarian Day",
    (8,21): "International Day of Remembrance and Tribute to the Victims of Terrorism",
    (8,22): "International Day Commemorating the Victims of Acts of Violence Based on Religion or Belief",
    (8,23): "International Day for the Remembrance of the Slave Trade and Its Abolition",
    (8,27): "World Lake Day",
    (8,29): "International Day against Nuclear Tests",
    (8,30): "International Day of the Victims of Enforced Disappearances",
    (8,31): "International Day for People of African Descent",
    
    # September
    (9,5): "International Day of Charity",
    (9,7): "World Duchenne Awareness Day",
    (9,7): "International Day of Clean Air for Blue Skies",
    (9,7): "International Day of Police Cooperation",
    (9,8): "International Literacy Day",
    (9,9): "International Day to Protect Education from Attack",
    (9,12): "United Nations Day for South-South Cooperation",
    (9,15): "International Day of Democracy",
    (9,16): "International Day of Science, Technology and Innovation for the South",
    (9,16): "International Day for Interventional Cardiology",
    (9,16): "International Day for the Preservation of the Ozone Layer",
    (9,17): "World Patient Safety Day",
    (9,18): "International Equal Pay Day",
    (9,20): "World Cleanup Day",
    (9,21): "International Day of Peace",
    (9,23): "International Day of Sign Languages",
    (9,25): "World Maritime Day",
    (9,26): "International Day for the Total Elimination of Nuclear Weapons",
    (9,27): "World Tourism Day",
    (9,28): "International Day for Universal Access to Information",
    (9,29): "International Day of Awareness of Food Loss and Waste",
    (9,30): "International Translation Day",
    
    # October
    (10,1): "International Day of Older Persons",
    (10,2): "International Day of Non-Violence",
    (10,5): "World Teachers' Day",
    (10,6): "World Habitat Day",
    (10,7): "World Cotton Day",
    (10,9): "World Post Day",
    (10,10): "World Mental Health Day",
    (10,11): "World Migratory Bird Day",
    (10,11): "International Day of the Girl Child",
    (10,13): "International Day for Disaster Risk Reduction",
    (10,15): "International Day of Rural Women",
    (10,16): "World Food Day",
    (10,17): "International Day for the Eradication of Poverty",
    (10,20): "World Statistics Day",
    (10,23): "International Day of the Snow Leopard",
    (10,24): "United Nations Day",
    (10,24): "World Development Information Day",
    (10,27): "World Day for Audiovisual Heritage",
    (10,29): "International Day of Care and Support",
    (10,31): "World Cities Day",
    
    # November
    (11,2): "International Day to End Impunity for Crimes against Journalists",
    (11,5): "World Tsunami Awareness Day",
    (11,6): "International Day for Preventing the Exploitation of the Environment in War and Armed Conflict",
    (11,10): "World Science Day for Peace and Development",
    (11,14): "World Diabetes Day",
    (11,15): "International Day for the Prevention of and Fight against All Forms of Transnational Organized Crime",
    (11,16): "International Day for Tolerance",
    (11,17): "World Day of Remembrance for Road Traffic Victims",
    (11,18): "World Day for the Prevention of and Healing from Child Sexual Exploitation, Abuse and Violence",
    (11,19): "World Toilet Day",
    (11,20): "Africa Industrialization Day",
    (11,20): "World Children's Day",
    (11,21): "World Television Day",
    (11,21): "World Philosophy Day",
    (11,24): "World Conjoined Twins Day",
    (11,25): "International Day for the Elimination of Violence against Women",
    (11,26): "World Sustainable Transport Day",
    (11,29): "International Day of Solidarity with the Palestinian People",
    (11,30): "Day of Remembrance for all Victims of Chemical Warfare",
    
    # December
    (12,1): "World AIDS Day",
    (12,2): "International Day for the Abolition of Slavery",
    (12,3): "International Day of Persons with Disabilities",
    (12,4): "International Day of Banks",
    (12,4): "International Day Against Unilateral Coercive Measures",
    (12,5): "International Volunteer Day for Economic and Social Development",
    (12,5): "World Soil Day",
    (12,7): "International Civil Aviation Day",
    (12,9): "International Day of Commemoration and Dignity of the Victims of the Crime of Genocide and of the Prevention of this Crime",
    (12,9): "International Anti-Corruption Day",
    (12,10): "Human Rights Day",
    (12,11): "International Mountain Day",
    (12,12): "International Day of Neutrality",
    (12,12): "International Universal Health Coverage Day",
    (12,18): "International Migrants Day",
    (12,18): "Arabic Language Day",
    (12,20): "International Human Solidarity Day",
    (12,21): "World Meditation Day",
    (12,21): "World Basketball Day",
    (12,25): "Christmas Day",
    (12,27): "International Day of Epidemic Preparedness",
    
    # Variable date holidays (these would need special calculation in the main code)
    # Note: These are placeholder entries - actual dates vary by year
    (1,15): "Martin Luther King Jr. Day",  # 3rd Monday of January
    (2,19): "Washington's Birthday (Presidents' Day)",  # 3rd Monday of February
    (5,27): "Memorial Day",  # Last Monday of May
    (9,2): "Labor Day",  # 1st Monday of September
    (10,14): "Columbus Day",  # 2nd Monday of October
    (11,28): "Thanksgiving Day",  # 4th Thursday of November
    (4,19): "Good Friday",  # Friday before Easter (example date)
    (4,22): "Easter Monday",  # Monday after Easter (example date)
    (5,6): "Early May Bank Holiday",  # 1st Monday of May
    (5,27): "Spring Bank Holiday",  # Last Monday of May
    (8,26): "Summer Bank Holiday"  # Last Monday of August
}

gregorian_events_fa = {
    # January
    (1,1): "روز سال نو",
    (1,4): "روز جهانی بریل (خط نابینایان)",
    (1,24): "روز جهانی آموزش",
    (1,26): "روز جهانی انرژی پاک",
    (1,27): "روز جهانی بزرگداشت یاد قربانیان هولوکاست",
    (1,28): "روز جهانی همزیستی مسالمت‌آمیز",
    
    # February
    (2,2): "روز جهانی تالاب‌ها",
    (2,4): "روز جهانی برادری انسانی",
    (2,6): "روز جهانی عدم تحمل ختنه زنان",
    (2,10): "روز جهانی حبوبات",
    (2,10): "روز جهانی پلنگ عربی",
    (2,11): "روز جهانی زنان و دختران در علم",
    (2,12): "روز جهانی پیشگیری از افراط‌گرایی خشونت‌آمیز که به تروریسم منجر می‌شود",
    (2,13): "روز جهانی رادیو",
    (2,17): "روز جهانی تاب‌آوری گردشگری",
    (2,20): "روز جهانی عدالت اجتماعی",
    (2,21): "روز جهانی زبان مادری",
    
    # March
    (3,1): "روز جهانی بدون تبعیض",
    (3,1): "روز جهانی علف‌های دریایی",
    (3,3): "روز جهانی حیات‌وحش",
    (3,5): "روز جهانی آگاهی درباره خلع سلاح و عدم اشاعه سلاح‌ها",
    (3,8): "روز جهانی زنان",
    (3,10): "روز جهانی زنان قاضی",
    (3,15): "روز جهانی مبارزه با اسلام‌هراسی",
    (3,20): "روز جهانی شادی",
    (3,20): "روز زبان فرانسوی",
    (3,21): "روز جهانی یخچال‌های طبیعی",
    (3,21): "روز جهانی محو تبعیض نژادی",
    (3,21): "روز جهانی جنگل‌ها",
    (3,21): "روز جهانی شعر",
    (3,21): "روز جهانی نوروز",
    (3,21): "روز جهانی سندرم داون",
    (3,22): "روز جهانی آب",
    (3,23): "روز جهانی هواشناسی",
    (3,24): "روز جهانی مبارزه با سل",
    (3,24): "روز جهانی حق دسترسی به حقیقت درباره نقض‌های فاحش حقوق بشر و کرامت قربانیان",
    (3,25): "روز جهانی یاد قربانیان برده‌داری و تجارت برده فراآتلانتیکی",
    (3,25): "روز جهانی همبستگی با کارکنان بازداشت یا مفقود سازمان ملل",
    (3,30): "روز جهانی بدون پسماند",
    
    # April
    (4,2): "روز جهانی آگاهی از اوتیسم",
    (4,4): "روز جهانی آگاهی و کمک در اقدام علیه مین",
    (4,5): "روز جهانی وجدان",
    (4,6): "روز جهانی ورزش برای توسعه و صلح",
    (4,7): "روز جهانی یادبود نسل‌کشی ۱۹۹۴ علیه قوم توتسی در رواندا",
    (4,7): "روز جهانی سلامت",
    (4,12): "روز جهانی پرواز فضایی انسان",
    (4,14): "روز جهانی بیماری چاگاس",
    (4,20): "روز زبان چینی",
    (4,21): "روز جهانی خلاقیت و نوآوری",
    (4,22): "روز جهانی زمین مادر",
    (4,23): "روز جهانی کتاب و حق مؤلف",
    (4,23): "روز زبان انگلیسی",
    (4,23): "روز زبان اسپانیایی",
    (4,24): "روز جهانی دختران در فناوری اطلاعات و ارتباطات",
    (4,24): "روز جهانی چندجانبه‌گرایی و دیپلماسی برای صلح",
    (4,25): "روز جهانی مالاریا",
    (4,25): "روز بین‌المللی نمایندگان سازمان ملل",
    (4,26): "روز جهانی یادبود فاجعه چرنوبیل",
    (4,26): "روز جهانی مالکیت فکری",
    (4,28): "روز جهانی ایمنی و سلامت در کار",
    (4,29): "روز جهانی یاد قربانیان زمین‌لرزه",
    (4,30): "روز جهانی جاز (موسیقی جاز)",
    
    # May
    (5,2): "روز جهانی تُن ماهی",
    (5,3): "روز جهانی آزادی مطبوعات",
    (5,5): "روز جهانی زبان پرتغالی",
    (5,8): "ایام یادبود و آشتی برای قربانیان جنگ جهانی دوم",
    (5,10): "روز جهانی درخت آرگان",
    (5,10): "روز جهانی پرندگان مهاجر",
    (5,12): "روز جهانی سلامت گیاه",
    (5,12): "روز وساک (سالروز تولد، بیداری و درگذشت بودا)",
    (5,15): "روز جهانی خانواده",
    (5,16): "روز جهانی همزیستی مسالمت‌آمیز",
    (5,16): "روز جهانی نور",
    (5,17): "روز جهانی ارتباطات و جامعه اطلاعاتی",
    (5,19): "روز جهانی بازی جوانمردانه",
    (5,20): "روز جهانی زنبور عسل",
    (5,21): "روز جهانی چای",
    (5,21): "روز جهانی تنوع فرهنگی برای گفت‌وگو و توسعه",
    (5,22): "روز جهانی تنوع زیستی",
    (5,23): "روز جهانی پایان دادن به فیستول زایمانی",
    (5,24): "روز جهانی بز کوهی مارخور",
    (5,25): "روز جهانی فوتبال",
    (5,29): "روز جهانی حافظان صلح سازمان ملل",
    (5,30): "روز جهانی سیب‌زمینی",
    (5,31): "روز جهانی بدون دخانیات",
    
    # June
    (6,1): "روز جهانی والدین",
    (6,3): "روز جهانی دوچرخه",
    (6,4): "روز جهانی کودکان بی‌گناه قربانی خشونت",
    (6,5): "روز جهانی محیط زیست",
    (6,5): "روز جهانی مبارزه با ماهیگیری غیرقانونی، گزارش‌نشده و کنترل‌نشده",
    (6,6): "روز زبان روسی",
    (6,7): "روز جهانی ایمنی غذا",
    (6,8): "روز جهانی اقیانوس‌ها",
    (6,10): "روز جهانی گفت‌وگو میان تمدن‌ها",
    (6,11): "روز جهانی بازی",
    (6,12): "روز جهانی مبارزه با کار کودکان",
    (6,13): "روز جهانی آگاهی درباره زالی (آلبینیسم)",
    (6,14): "روز جهانی اهداکنندگان خون",
    (6,15): "روز جهانی آگاهی از آزار سالمندان",
    (6,16): "روز جهانی حواله‌های خانوادگی (وجوه ارسالی کارگران مهاجر)",
    (6,17): "روز جهانی مبارزه با بیابان‌زایی و خشکسالی",
    (6,18): "روز جهانی آشپزی پایدار",
    (6,18): "روز جهانی مقابله با نفرت‌پراکنی",
    (6,19): "روز جهانی حذف خشونت جنسی در درگیری‌ها",
    (6,20): "روز جهانی پناهندگان",
    (6,21): "روز جهانی یوگا",
    (6,21): "روز جهانی بزرگداشت انقلاب تابستانی (طولانی‌ترین روز سال)",
    (6,23): "روز خدمات عمومی سازمان ملل",
    (6,23): "روز جهانی بیوه‌گان",
    (6,24): "روز جهانی زنان در دیپلماسی",
    (6,25): "روز جهانی دریانورد",
    (6,26): "روز جهانی مبارزه با مواد مخدر و قاچاق غیرقانونی",
    (6,26): "روز جهانی حمایت از قربانیان شکنجه",
    (6,27): "روز جهانی ناشنوایی و نابینایی هم‌زمان",
    (6,27): "روز جهانی بنگاه‌های خرد، کوچک و متوسط",
    (6,29): "روز جهانی نواحی استوایی",
    (6,30): "روز جهانی شهاب‌سنگ‌ها",
    (6,30): "روز جهانی پارلمانیسم",
    
    # July
    (7,5): "روز جهانی تعاون",
    (7,6): "روز جهانی توسعه روستایی",
    (7,7): "روز جهانی زبان سواحیلی",
    (7,7): "روز جهانی اسب",
    (7,11): "روز جهانی جمعیت",
    (7,11): "روز جهانی یادبود نسل‌کشی ۱۹۹۵ در سربرنیتسا",
    (7,12): "روز جهانی مقابله با طوفان‌های شن و گردوغبار",
    (7,12): "روز جهانی امید",
    (7,15): "روز جهانی مهارت‌های جوانان",
    (7,18): "روز جهانی نلسون ماندلا",
    (7,20): "روز جهانی شطرنج",
    (7,20): "روز جهانی ماه",
    (7,25): "روز جهانی زنان و دختران آفریقایی‌تبار",
    (7,25): "روز جهانی پیشگیری از غرق‌شدگی",
    (7,25): "روز جهانی سلامت قضایی",
    (7,28): "روز جهانی هپاتیت",
    (7,30): "روز جهانی دوستی",
    (7,30): "روز جهانی مبارزه با قاچاق انسان",
    
    # August
    (8,6): "روز جهانی آگاهی از نیازها و چالش‌های توسعه‌ای کشورهای محصور در خشکی",
    (8,9): "روز جهانی مردم بومی جهان",
    (8,11): "روز جهانی ساز استیل‌پن (Steelpan)",
    (8,12): "روز جهانی جوانان",
    (8,19): "روز جهانی بشردوستی",
    (8,21): "روز جهانی یادبود و ادای احترام به قربانیان تروریسم",
    (8,22): "روز جهانی بزرگداشت قربانیان خشونت ناشی از دین یا باور",
    (8,23): "روز جهانی یادبود تجارت برده و لغو آن",
    (8,27): "روز جهانی دریاچه‌ها",
    (8,29): "روز جهانی مقابله با آزمایش‌های هسته‌ای",
    (8,30): "روز جهانی قربانیان ناپدیدسازی اجباری",
    (8,31): "روز جهانی مردم آفریقایی‌تبار",
    
    # September
    (9,5): "روز جهانی نیکوکاری",
    (9,7): "روز جهانی آگاهی از بیماری دوشن",
    (9,7): "روز جهانی هوای پاک برای آسمان آبی",
    (9,7): "روز جهانی همکاری پلیس",
    (9,8): "روز جهانی سوادآموزی",
    (9,9): "روز جهانی حمایت از آموزش در برابر حمله",
    (9,12): "روز همکاری جنوب–جنوب سازمان ملل",
    (9,15): "روز جهانی دموکراسی",
    (9,16): "روز جهانی علم، فناوری و نوآوری برای کشورهای جنوب",
    (9,16): "روز جهانی قلب و کاردیولوژی مداخله‌ای",
    (9,16): "روز جهانی حفاظت از لایه اوزون",
    (9,17): "روز جهانی ایمنی بیمار",
    (9,18): "روز جهانی برابری دستمزد",
    (9,20): "روز جهانی پاکسازی زمین",
    (9,21): "روز جهانی صلح",
    (9,23): "روز جهانی زبان‌های اشاره",
    (9,25): "روز جهانی دریانوردی",
    (9,26): "روز جهانی حذف کامل سلاح‌های هسته‌ای",
    (9,27): "روز جهانی گردشگری",
    (9,28): "روز جهانی دسترسی همگانی به اطلاعات",
    (9,29): "روز جهانی آگاهی از اتلاف و ضایعات مواد غذایی",
    (9,30): "روز جهانی ترجمه",
    
    # October
    (10,1): "روز جهانی سالمندان",
    (10,2): "روز جهانی پرهیز از خشونت",
    (10,5): "روز جهانی معلمان",
    (10,6): "روز جهانی اسکان بشر",
    (10,7): "روز جهانی پنبه",
    (10,9): "روز جهانی پست",
    (10,10): "روز جهانی سلامت روان",
    (10,11): "روز جهانی پرندگان مهاجر",
    (10,11): "روز جهانی دختران",
    (10,13): "روز جهانی کاهش خطر بلایا",
    (10,15): "روز جهانی زنان روستایی",
    (10,16): "روز جهانی غذا",
    (10,17): "روز جهانی ریشه‌کنی فقر",
    (10,20): "روز جهانی آمار",
    (10,23): "روز جهانی پلنگ برفی",
    (10,24): "روز سازمان ملل متحد",
    (10,24): "روز جهانی اطلاع‌رسانی توسعه",
    (10,27): "روز جهانی میراث سمعی و بصری",
    (10,29): "روز جهانی مراقبت و پشتیبانی",
    (10,31): "روز جهانی شهرها",
    
    # November
    (11,2): "روز جهانی پایان دادن به مصونیت عاملان جنایت علیه خبرنگاران",
    (11,5): "روز جهانی آگاهی از سونامی",
    (11,6): "روز جهانی جلوگیری از بهره‌کشی از محیط‌زیست در جنگ و درگیری",
    (11,10): "روز جهانی علم برای صلح و توسعه",
    (11,14): "روز جهانی دیابت",
    (11,15): "روز جهانی پیشگیری و مبارزه با همه اشکال جرائم سازمان‌یافته فراملی",
    (11,16): "روز جهانی مدارا",
    (11,17): "روز جهانی یاد قربانیان حوادث رانندگی",
    (11,18): "روز جهانی پیشگیری و درمان استثمار و آزار جنسی کودکان",
    (11,19): "روز جهانی توالت",
    (11,20): "روز صنعتی‌سازی آفریقا",
    (11,20): "روز جهانی کودک",
    (11,21): "روز جهانی تلویزیون",
    (11,21): "روز جهانی فلسفه",
    (11,24): "روز جهانی دوقلوهای به‌هم‌چسبیده",
    (11,25): "روز جهانی محو خشونت علیه زنان",
    (11,26): "روز جهانی حمل‌ونقل پایدار",
    (11,29): "روز جهانی همبستگی با مردم فلسطین",
    (11,30): "روز یادبود همه قربانیان جنگ‌های شیمیایی",
    
    # December
    (12,1): "روز جهانی ایدز",
    (12,2): "روز جهانی لغو برده‌داری",
    (12,3): "روز جهانی افراد دارای معلولیت",
    (12,4): "روز جهانی بانک‌ها",
    (12,4): "روز جهانی مقابله با اقدامات قهری یک‌جانبه",
    (12,5): "روز جهانی داوطلبان برای توسعه اقتصادی و اجتماعی",
    (12,5): "روز جهانی خاک",
    (12,7): "روز جهانی هوانوردی غیرنظامی",
    (12,9): "روز جهانی بزرگداشت و کرامت قربانیان جنایت نسل‌کشی و پیشگیری از آن",
    (12,9): "روز جهانی مبارزه با فساد",
    (12,10): "روز جهانی حقوق بشر",
    (12,11): "روز جهانی کوه",
    (12,12): "روز جهانی بی‌طرفی",
    (12,12): "روز جهانی پوشش همگانی سلامت",
    (12,18): "روز جهانی مهاجران",
    (12,18): "روز جهانی زبان عربی",
    (12,20): "روز جهانی همبستگی انسانی",
    (12,21): "روز جهانی مدیتیشن (مراقبه)",
    (12,21): "روز جهانی بسکتبال",
    (12,25): "روز کریسمس",
    (12,27): "روز جهانی آمادگی در برابر همه‌گیری‌ها",
    
    # تعطیلات متغیر (نیاز به محاسبه خاص در کد اصلی)
    # توجه: اینها تاریخ‌های نمونه هستند - تاریخ واقعی هر سال متفاوت است
    (1,15): "روز مارتین لوتر کینگ جونیور",  # سومین دوشنبه ژانویه
    (2,19): "روز تولد جورج واشنگتن (روز رؤسای جمهور)",  # سومین دوشنبه فوریه
    (5,27): "روز یادبود قربانیان جنگ",  # آخرین دوشنبه ماه مه
    (9,2): "روز کارگر",  # اولین دوشنبه سپتامبر
    (10,14): "روز کلمبوس",  # دومین دوشنبه اکتبر
    (11,28): "روز شکرگزاری",  # چهارمین پنج‌شنبه نوامبر
    (4,19): "جمعه خوب (از تعطیلات عید پاک)",  # جمعه قبل از عید پاک
    (4,22): "دوشنبه عید پاک",  # دوشنبه بعد از عید پاک
    (5,6): "تعطیلی بانکی ابتدای ماه مه",  # اولین دوشنبه ماه مه
    (5,27): "تعطیلی بانکی بهاری",  # آخرین دوشنبه ماه مه
    (8,26): "تعطیلی بانکی تابستانی"  # آخرین دوشنبه ماه اوت
}

gregorian_holidays = {
    # Fixed holidays (same date every year)
    (1,1): 1,   # New Year's Day
    (6,19): 1,  # Juneteenth National Independence Day
    (7,4): 1,   # Independence Day
    (11,11): 1, # Veterans Day
    (12,25): 1, # Christmas Day
    (12,26): 1, # Boxing Day (UK)
    
    # Note: The following holidays have variable dates and would need special calculation:
    # - Martin Luther King Jr. Day (3rd Monday of January)
    # - Washington's Birthday/Presidents' Day (3rd Monday of February)  
    # - Memorial Day (Last Monday of May)
    # - Labor Day (1st Monday of September)
    # - Columbus Day (2nd Monday of October)
    # - Thanksgiving Day (4th Thursday of November)
    # - Good Friday (Friday before Easter)
    # - Easter Monday (Monday after Easter)
    # - Early May Bank Holiday (1st Monday of May)
    # - Spring Bank Holiday (Last Monday of May)
    # - Summer Bank Holiday (Last Monday of August)
}
